ARG JDK_VERSION
ARG GIT_VERSION
ARG GRADLE_VERSION=9.6.1
ARG OS=debian

FROM kubernetesloong64/git-loong64:${GIT_VERSION}-${OS} AS git-stage
FROM kubernetesloong64/gradle-loong64:${GRADLE_VERSION}-${JDK_VERSION}-${OS}

COPY --from=git-stage /usr/local /usr/local

RUN apt-get update \
    && apt-get install -y --no-install-recommends libcurl4-gnutls ca-certificates less \
    && git --version \
    && git clone https://github.com/kubernetes-loong64/git-loong64.git /tmp/git-loong64 \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/git-loong64
